name: MFE S3 Bucket Deployment ðŸš€

on:
  push:
    branches:
      - open-release/redwood.nelp
      - open-rc/redwood.nelp

  pull_request:
    branches:
       - "**open-rc**"

jobs:
  deployment:
    uses: nelc/actions-hub/.github/workflows/mfe-s3-bucket-deployment.yml@main
    with:
     PROD_BRANCH: 'open-release/redwood.nelp'
    secrets: inherit
